name: mtb-recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - jupyterlab
  - matplotlib
  - pip
  - pip:
      - scikit-surprise   # <-- this is the Surprise library