name: mtb-recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Bump to 3.11 for better compatibility
  - pandas
  - numpy
  - scikit-learn
  - surprise  # This is scikit-surprise from conda-forge
  - jupyter
  - matplotlib