name: mtb-recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24
  - pandas
  - scikit-learn
  - scikit-surprise
  - pip
  - pip:
    - jupyterlab
    - ipykernel
    # add any pip-only packages here